version: '3.8'
services:
  gateway:
    build:
      context: ./apps/gateway
    volumes:
      - ./apps/gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - event
      - user
      - tickets
    environment:
      - EVENTS_SERVICE_URL=http://event:3003
      - USERS_SERVICE_URL=http://user:3020
      - TICKETS_SERVICE_URL=http://tickets:3040
  event:
    build:
      context: ./apps/events
    environment:
      - DATABASE_URL=mongodb+srv://daadaamed:ZzQoHzZm7mdeAoMP@users.8ltf5ky.mongodb.net/Events-4webd
    ports:
      - "3003:3003"

  user:
    build:
      context: ./apps/users
    environment:
      - DATABASE_URL=mongodb+srv://daadaamed:ZzQoHzZm7mdeAoMP@users.8ltf5ky.mongodb.net/Users-4webd
    ports:
      - "3020:3020"

  tickets:
    build:
      context: ./apps/tickets
    environment:
      - DATABASE_URL=mongodb+srv://daadaamed:ZzQoHzZm7mdeAoMP@users.8ltf5ky.mongodb.net/Tickets-4webd
    ports:
      - "3040:3040"

  user-db:
    image: mongo:latest
    volumes:
      - user-db-volume:/data/db

volumes:
  user-db-volume: {}

